FROM python:3.7-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r ./requirements.txt

ENV PYTHONPATH=".:$PYTHONPATH"

COPY entrypoint.sh ./
COPY nekooo ./nekooo/

CMD ["gunicorn", "-b", "0.0.0.0:5000", "--chdir", "nekooo", "main:app"]
